### ISSUE TITLE
--sensitive mode crashes in multiple ways

### ISSUE THREAD

**Issue by johnemajor** [BilkentCompGen/tardis#10]
Here is the command I am running: 

` for i in `seq 0 23`; 
 do  
echo tardis --bamlist /efs/WGS/data/WGS/ILMN_exptA/b37/cnv/tardis/all.bam --ref /home/ubuntu/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta --sonic /efs/WGS/data/WGS/ILMN_exptA/b37/cnv/tardis/sonic-prebuilt/human_g1k_v37.sonic  --sensitive  --mei 'notags' --read-cluster 40 --first-chr $i --last-chr $i --out SENSITIVE_tardis_out_$i`

I get the following errors during processing:

#1
`[TARDIS INPUT ERROR] Unable to open file divet//NA12878-A.sam_DIVET.vh in read mode.
`
#2 
`Remapping:
                Sample: NA12878
                Library: A
Sequence length: 151 bp. Error threshold is set to 7 bp.
You can override this value using the -e parameter.
[PE mode Warning] Sequence lengths are different,  read #1 is clipped to match.
Cannot allocate memory. Currently addressed memory = 1579.05 MB, requested memory = 0.00 MB.
Check the available main memory, and if you have user limits (ulimit -v).
`
fwiw, ulimit -v is unlimited.  And the box I am running on has 96 cores with 365Gb of memory

When I had run tardis with default parameters it ran to completion.  There seems to be several issues with mrfast, it seems unlikely it's a versioning issue as their codebase does not appear to have changed in many years.

**Comment by calkan** [comment]
quick answer: don't use sensitive mode. We have deprecated that part of the code internally, and will remove in next release.

**Comment by johnemajor** [comment]
Got it! Thanks.
