### ISSUE TITLE
What does CNV likelihood mean?

### ISSUE THREAD

**Issue by weishwu** [BilkentCompGen/tardis#11]
Hi,

What does CNVL (CNV likelihood) mean exactly in the tardis output? What's the cutoff would you recommend to filter by?

Thanks,

**Comment by asylvz** [comment]
Hi,
 
We calculate a likelihood score for each putative SV, provided the read pair, read depth and split read signatures. Default settings are the recommended ones but I should note that the lower the CNVL, the more confident the SV is. 

So if you want more confident calls, you can filter higher ones. That's up your expectation from the call set. This would especially be more significant for interspersed duplications which are more error-prone.


More info about the CNVL is given in the paper: https://doi.org/10.1093/bioinformatics/btz237

Best,

**Comment by weishwu** [comment]
Thanks!
