### ISSUE TITLE
Questions concerning exclusion of regions and VCF output

### ISSUE THREAD

**Issue by CorinnaErnst** [BilkentCompGen/tardis#14]
Dear developers,

thank you for providing TARDIS.

I've got some questions regarding parameter setting and VCF output. Please let me know in case I have simply overlooked the manual where these issues are explained.

(1) Does specification of --gaps  [gaps file] results in ignoring the regions given in the .bed file in the SV calling process?

(2) What does mfilt, i.e., Mobile Element Filter, exactly means? That this is a known MEI? I wonder what differentiates the MEIs with FILTER entries PASS and mfilt.

(3) Using TARDIS v1.0.8, the resulting VCF contains exclusively value 255 in the QUAL column. 
Does this mean that something went wrong? Is TARDIS expected to report a (varying) QUAL per putative SV and if so, how is it defined?

Many thanks!

**Comment by asylvz** [comment]
Thank you for your interest:

1 - Yes, we ignore these regions
2 - Yes, these correspond to the known satellite regions, so we filter them in the output. 
3 - 255 is a hard coded number, we don't report the actual quality value for each variant. But thank you for reporting this, we should definitely consider this as an issue.

Best

**Comment by CorinnaErnst** [comment]
Thank you for the quick response! 
Best wishes
