### ISSUE TITLE
Only MEI detected

### ISSUE THREAD

**Issue by ebattistella** [BilkentCompGen/tardis#15]
Dear authors,

Thank you for this great tool!

I am trying to use tardis on NA12878 with the reference hg19 and the sonic file provided at https://github.com/BilkentCompGen/sonic-prebuilt.
The command I used is:
tardis -i NA12878_hg19.bwamem.sorted.bam  --ref genome.fa --sonic csc_hg19.sonic \
       -o ./hg_19
However, the final vcf file only reports MEI, which is surprising as other variants have been detected for each chromosome separately. Besides, no insertion is detected for any chromosome.

The command, reference, and sonic files should be correct, as they have been used successfully with HG002.
I have attached the log file for NA12878.

Could you please help me with this issue and explain how the final variants are defined from the variants on each chromosome?
[hg_19-tardis.log](https://github.com/BilkentCompGen/tardis/files/10855506/hg_19-tardis.log)

**Comment by asylvz** [comment]
Hi, do you know the coverage of your genome? If it's too low, then this might be expected.

For insertions; short illumina reads are not very successful in general for accurate detection, this is not only for Tardis. But you should expect to see some insertions if you have enough coverage.

Best,
Arda

**Comment by ebattistella** [comment]
Thank you for your answer!
The coverage of the file I am using is 30x. Can it be an issue?

For HG002, the coverage is 60x, so I feel like it should be enough to find some insertions.

Best,
Enzo

**Comment by asylvz** [comment]
30x is enough but are you sure it is 30x? The log file says that there are 736530 reads, which is very very low. And the mean is very low too. Please check the overall depth of coverage of your sample. You may also want to check the number of reads in the bam file, it should be ~9-10 digits.

**Comment by calkan** [comment]
Hi.  Depth of coverage is not the problem. The log file shows the average fragment length is 148 bp and reads are 150 bp. Therefore the reads overlap fully, leaving no gap between them. This makes read pair analysis impossible, and the split read module in TARDIS is for reducing false positives and improving breakpoint resolution. You will need a purely split-read based method for this data set.
