### ISSUE TITLE
[SONIC INPUT ERROR] Unable to open file /home/gamze/Downloads/tardisss/ucsc_hg19.sonic in read mode.

### ISSUE THREAD

**Issue by gamzemdn** [BilkentCompGen/tardis#17]
Hello,
I get this error with my own docker built or alkanlab build. I modified the test_tardis_docker.sh file for easy analyses and here is my command line:

sudo docker pull alkanlab/tardis
sh '/home/gamze/Downloads/tardis-master/test_tardis_docker.sh' 

I am copying my .sh file below and adding the screenshot. Thanks in advance!

#!/bin/bash

WGET_EXE=`which wget`

if [ -z ${WGET_EXE} ]
then
        echo "WGET binary is not in your PATH. Either move the WGET binary to your PATH, or add its location to the PATH environment variable."
else
        echo "Found WGET at " ${WGET_EXE}.
fi

SAMTOOLS_EXE=`which samtools`

if [ -z ${SAMTOOLS_EXE} ]
then
        echo "SAMTOOLS binary is not in your PATH. Either move the SAMTOOLS binary to your PATH, or add its location to the PATH environment variable."
else
        echo "Found SAMTOOLS at " ${SAMTOOLS_EXE}.
fi

# these are the parameters. Commend out the WGET lines aboove if they are predownloaded
INPUTBAM=/home/gamze/Downloads/tardisss/na24385.bam
REF=home/gamze/Downloads/tardisss/GRCh38_full_analysis_set_plus_decoy_hla.fa
SONIC=home/gamze/Downloads/tardisss/ucsc_hg19.sonic

${SAMTOOLS_EXE} quickcheck $INPUTBAM
if [ $? -eq 0 ] 
then
	echo $INPUTBAM " seems to be downloaded correctly according to samtools quickcheck";
else
	echo $INPUTBAM " seems NOT to be downloaded correctly according to samtools quickcheck. Please rerun this script.";
	exit 1;
fi

# pull docker image. Comment this out if it is already pulled
# docker pull alkanlab/tardis

# ready to call TARDIS 
sudo docker run --user=$UID -w ${PWD} -v ${PWD}:/input -v ${PWD}:/output alkanlab/tardis  -i /input/$INPUTBAM --ref /input/$REF --sonic /input/$SONIC --out **/output/NA11930-chrom20-demo**

![Screenshot from 2024-09-17 01-02-56](https://github.com/user-attachments/assets/d6131bb0-8b3c-43b4-aef7-a567b55429a9)

**Comment by calkan** [comment]
do not write the full paths for the INPUTBAM, SONIC, and REF parameters. The test script is meant to be a simple test, it will just assume that those files are in your current working directory. If you want to access to those files from somewhere else, change the last line in the test script:

docker run --user=$UID -w ${PWD} -v ${PWD}:/input -v ${PWD}:/output alkanlab/tardis  -i /input/$INPUTBAM --ref /input/$REF --sonic /input/$SONIC --out /output/NA11930-chrom20-demo

to something like:

MYDIR=/home/gamze/Downloads/

docker run --user=$UID -w ${MYDIR} -v ${MYDIR}:/input -v ${PWD}:/output alkanlab/tardis  -i /input/$INPUTBAM --ref /input/$REF --sonic /input/$SONIC --out /output/NA11930-chrom20-demo

and again remove the path from those parameters, just have them as ucsc_hg19.sonic

by the way you are also using GRCh38 reference and ucsc_hg19.sonic;  these are incompatible, not the same version of the reference genome.

**Comment by gamzemdn** [comment]
Hello again, 

Thank you very much for quick reply Hocam. It seems to be working now. I am using GRCH38.sonic file is it correct? I read in one of the issues you mentioned ucsc_hg38.sonic but I couldn't find that.

**Comment by gamzemdn** [comment]
Analyses is completed but only chr1 is in vcf not other chromosonmes? What should I do?

Thanks in advance

**Comment by calkan** [comment]
GRCH38.sonic file is correct. If your BAM file contains other chromosomes, it should have worked for all of them. I will let @asylvz take it from here to help you get it running

**Comment by gamzemdn** [comment]
I have 7 other sv detection tools run on 8 different whole genome samples and this is one of them. Other 7 tools reported all the chromosomes
I am also adding last screenshot below

![Screenshot from 2024-09-19 19-02-26](https://github.com/user-attachments/assets/31465235-e645-46b8-9815-c3e8b3075c20)

Best Regards,

**Comment by asylvz** [comment]
Hi @gamzemdn, I think the docker image is not up to date but can you try running with "--no-interdup" flag. I also suggest trying the latest github version instead of the docker image if you can.

Arda

**Comment by gamzemdn** [comment]
Hi!
My own docker build now finished chr1 and moved to chr2, I believe I won't have any problem anymore. I am closing the issue now.  If I encounter any problem in the future, I would open a new issue. Thank you for your support.

Best,
