### ISSUE TITLE
Segmentation fault with GRCh38

### ISSUE THREAD

**Issue by DavidEGray** [BilkentCompGen/tardis#2]
Hello.

Tardis is running fine with GRCh37, but when I try to run it on GRCh38, I always get a segmentation fault.  

Any suggestions?

**Comment by asylvz** [comment]
Can you please write the command that you're using? You should not use the same sonic file with GRCh38. And if possible, send me the gdb output so that I can track it.

**Comment by DavidEGray** [comment]
Yes, I made a GRCh38 sonic file.

Here's the command:
tardis -i sample.bam --ref GRCh38_full_analysis_set_plus_decoy_hla.fa --sonic GRCh38.sonic --out sample

I'm not sure what you mean by gdb output.

**Comment by asylvz** [comment]
gdb is the debugger output but I don't need it anymore, I found the bug. I'll fix it and let you know.

**Comment by asylvz** [comment]
You can try with the newest commit and use the ucsc_hg38.sonic file in the aux directory for GRC38. Let me know if you encounter a problem.

**Comment by DavidEGray** [comment]
Thank you.  Using the latest commit and the sonic file you mentioned, it got a good bit further, but still ended with a segmentation fault.

**Comment by calkan** [comment]
can you share your BAM file with us so we can replicate the problem on our end? Also, please copy/paste the screen output, maybe we can figure it out at which step it fails.

**Comment by asylvz** [comment]
I have made some fixes, it should be working now. Please let me know if you encounter any other issues.
