### ISSUE TITLE
test command error

### ISSUE THREAD

**Issue by rchikka** [BilkentCompGen/tardis#4]
Hi,
I'm trying to install your tool, tardis and I keep getting the error "-i: command not found" when I run the test command you gave. Attached is the logfile for the full installation ouptut. 
[tardis_logfile.txt](https://github.com/BilkentCompGen/tardis/files/2578062/tardis_logfile.txt)
Thanks in advance!

**Comment by calkan** [comment]
the only way this could happen is that tardis binary is not in your PATH.

See at the top of the script:

TARDIS_EXE=`which tardis`

"which tardis" command returns NULL in your case. Just move the tardis binary somewhere in your path, or change the {TARDIS_EXE} to the exact location of the binary, something like

TARDIS_EXE=/home/rchikka/binaries/tardis

**Comment by calkan** [comment]
commit 7d58da9 adds path checks to warn about missing PATH.
