### ISSUE TITLE
Mapping Issues

### ISSUE THREAD

**Issue by rchikka** [BilkentCompGen/tardis#5]
I installed liblzma and libbz2, but I am having trouble mapping them so that tardis can use them to compile with the 'make libs' command. How should I proceed? Thank you in advance!

**Comment by calkan** [comment]
they are dependencies for htslib, not TARDIS. Did you install their development libraries? liblzma-dev and libbz2-dev.

**Comment by smangul1** [comment]
Rahul, Can you please send exactly the command you have run for installation
Can, 
Can you please send the command to install development libraries?
Serghei

**Comment by calkan** [comment]
sudo apt-get install libbz2-dev liblzma-dev zlib1g-dev 

I added it to README.  Alternatively you can use docker: https://hub.docker.com/r/alkanlab/tardis/

**Comment by smangul1** [comment]
Thanks, Can! Unfortunately, we don't have sudo on UCLA cluster! Also docker is not supported by the cluster. Any alternatives? We really want to include your tool in the benchmarking study but we have hard time installing it.

**Comment by rchikka** [comment]
I did not install the development libraries I installed these instead:
https://github.com/enthought/bzip2-1.0.6
https://github.com/kobolabs/liblzma
I can't use apt-get to get the development libraries, and I don't have sudo
authorization. Is there another way other than git cloning and apt-get to
get these libraries?

**Comment by calkan** [comment]
they are all htslib dependencies (www.htslib.org), and I can't change htslib myself. As long as you have the libhts.so file under htslib/ directory, TARDIS should compile. For htslib compilation you should refer to them.  I will try to see if I can workaround that by including lzma, zlib, libbz2 somehow.

I am adding a precompiled binary of TARDIS for you though.

[tardis-0.7.5_x86_64.gz](https://github.com/BilkentCompGen/tardis/files/2649581/tardis-0.7.5_x86_64.gz)

**Comment by rchikka** [comment]
These were the commands I ran to install the libraries into htslib within
tardis:

mkdir research
  939  cd research
  940  ls
  941  git clone https://github.com/BilkentCompGen/tardis.git --recursive
  947  cd research
  948  ls
  949  cd tardis
  950  ls
  951  make libs
  952  ls
  953  cd htslib
  954  ls
  955  cd cram
  956  ls
  957  cd cram_io.c
  958  cd
  959  ls
  960  cd research
  961  cd tardis
  962  cd htslib
  963  ls
  964  git clone https://github.com/kobolabs/liblzma.git
  965  pwd
  966  ./configure --prefix=/u/home/r/rchikka1/research/tardis/htslib
  967  ls
  968  cd liblzma
  969  ./configure --prefix=/u/home/r/rchikka1/research/tardis/htslib
  970  make
  971  make install
  972  ls
  973  cd
  974  cd research
  975  cd tardis
  976  ls
  977  cd htslib
  978  ls
  979  cd lib
  980  ls
  981  cd
  982  cd research/tardis/htslib
  983  ls
  984  git clone https//github.com/enthought/bzip2-1.0.6
  985  git clone https://github.com/enthought/bzip2-1.0.6
  986  ls
  987  pwd
  988  cd bzip2-1.0.6
  989  ls
  990  make
  991  make install PREFIX=/u/home/r/rchikka1/research/tardis/htslib
  992  ls
  993  cd
  994  ls
  995  cd research
  996  ls
  997  cd tardis
  998  ls
  999  make libs

**Comment by calkan** [comment]
I can't really help you install htslib, it is not my software. What you did looks like should be able to compile htslib though. Then make libs might give you errors but as long as libhts.so is there, it is fine. 
Or you can skip htslib compilation and compile the other two:  

make -C vh && make -C sonic

then just make.

**Comment by calkan** [comment]
there is a workaround I found after reading htslib INSTALL, but it will disable any CRAM usage. If you only have BAMs, then:

cd htslib && autoheader && autoconf && ./configure --disable-lzma && --disable-bz2
cd ..
make -C vh
make -C sonic
make

this should give you a BAM-only TARDIS.  I also added this to the Makefile  (make nocram) and updated README.

**Comment by rchikka** [comment]
Professor Alkan, we used the precompiled Tardis binary that you sent us but we lack the liblzma directory needed to run Tardis. Do we need to install liblzma separately from Tardis, and if so how do we map it to the Tardis program? Thank you in advance!
