### ISSUE TITLE
tardis for RN6 ?

### ISSUE THREAD

**Issue by colindaven** [BilkentCompGen/tardis#6]
Hi,

I'm interested in Tardis for mouse and rat. Do you know where to get sonic or the required files, eg. --gaps assembly gaps file - for these species?

Or is it intended as a human only caller ?

Thanks,
Colin

**Comment by calkan** [comment]
Hi

mm9 and mm10 are available here: https://github.com/BilkentCompGen/sonic-prebuilt

for rn6, check out the README in sonic  repository. It has documentation on how to get those necessart files: https://github.com/calkan/sonic/blob/master/README.md

**Comment by colindaven** [comment]
Thanks, will give it a go.
