### ISSUE TITLE
using no --sensitive mode.

### ISSUE THREAD

**Issue by nordhuang** [BilkentCompGen/tardis#7]
Cannot find chromosome name 1 in bam sample  
Cannot find chromosome name 2 in bam sample
Cannot find chromosome name 3 in bam sample
Cannot find chromosome name 4 in bam sample
Cannot find chromosome name 5 in bam sample
Cannot find chromosome name 6 in bam sample
Cannot find chromosome name 7 in bam sample
Cannot find chromosome name 8 in bam sample
Cannot find chromosome name 9 in bam sample
Cannot find chromosome name 10 in bam sample
Cannot find chromosome name 11 in bam sample
Cannot find chromosome name 12 in bam sample
Cannot find chromosome name 13 in bam sample
Cannot find chromosome name 14 in bam sample
Cannot find chromosome name 15 in bam sample
Cannot find chromosome name 16 in bam sample
Cannot find chromosome name 17 in bam sample
Cannot find chromosome name 18 in bam sample
Cannot find chromosome name 19 in bam sample
Cannot find chromosome name 20 in bam sample
Cannot find chromosome name 21 in bam sample
Cannot find chromosome name 22 in bam sample
Cannot find chromosome name X in bam sample
Cannot find chromosome name Y in bam sample
Cannot find chromosome name MT in bam sample
Cannot find chromosome name GL000207.1 in bam sample
Cannot find chromosome name GL000226.1 in bam sample
Cannot find chromosome name GL000229.1 in bam sample
Cannot find chromosome name GL000231.1 in bam sample
Cannot find chromosome name GL000210.1 in bam sample
Cannot find chromosome name GL000239.1 in bam sample
Cannot find chromosome name GL000235.1 in bam sample
Cannot find chromosome name GL000201.1 in bam sample
Cannot find chromosome name GL000247.1 in bam sample
Cannot find chromosome name GL000245.1 in bam sample
Cannot find chromosome name GL000197.1 in bam sample
Cannot find chromosome name GL000203.1 in bam sample
Cannot find chromosome name GL000246.1 in bam sample
Cannot find chromosome name GL000249.1 in bam sample
Cannot find chromosome name GL000196.1 in bam sample
Cannot find chromosome name GL000248.1 in bam sample
Cannot find chromosome name GL000244.1 in bam sample
Cannot find chromosome name GL000238.1 in bam sample
Cannot find chromosome name GL000202.1 in bam sample
Cannot find chromosome name GL000234.1 in bam sample
Cannot find chromosome name GL000232.1 in bam sample
Cannot find chromosome name GL000206.1 in bam sample
Cannot find chromosome name GL000240.1 in bam sample
Cannot find chromosome name GL000236.1 in bam sample
Cannot find chromosome name GL000241.1 in bam sample
Cannot find chromosome name GL000243.1 in bam sample
Cannot find chromosome name GL000242.1 in bam sample
Cannot find chromosome name GL000230.1 in bam sample
Cannot find chromosome name GL000237.1 in bam sample
Cannot find chromosome name GL000233.1 in bam sample
Cannot find chromosome name GL000204.1 in bam sample
Cannot find chromosome name GL000198.1 in bam sample
Cannot find chromosome name GL000208.1 in bam sample
Cannot find chromosome name GL000191.1 in bam sample
Cannot find chromosome name GL000227.1 in bam sample
Cannot find chromosome name GL000228.1 in bam sample
Cannot find chromosome name GL000214.1 in bam sample
Cannot find chromosome name GL000221.1 in bam sample
Cannot find chromosome name GL000209.1 in bam sample
Cannot find chromosome name GL000218.1 in bam sample
Cannot find chromosome name GL000213.1 in bam sample
Cannot find chromosome name GL000211.1 in bam sample
Cannot find chromosome name GL000199.1 in bam sample
Cannot find chromosome name GL000217.1 in bam sample
Cannot find chromosome name GL000216.1 in bam sample
Cannot find chromosome name GL000215.1 in bam sample
Cannot find chromosome name GL000205.1 in bam sample
Cannot find chromosome name GL000219.1 in bam sample
Cannot find chromosome name GL000224.1 in bam sample
Cannot find chromosome name GL000223.1 in bam sample
Cannot find chromosome name GL000195.1 in bam sample
Cannot find chromosome name GL000212.1 in bam sample
Cannot find chromosome name GL000222.1 in bam sample
Cannot find chromosome name GL000200.1 in bam sample
Cannot find chromosome name GL000193.1 in bam sample
Cannot find chromosome name GL000194.1 in bam sample
Cannot find chromosome name GL000225.1 in bam sample
Cannot find chromosome name GL000192.1 in bam sample
using no --sensitive mode.
what does it mean?

**Comment by asylvz** [comment]
what is your command?

**Comment by calkan** [comment]
Your BAM file, reference FASTA file and SONIC file don't match to each other (any pairs of them). Check which reference you used for generating the BAM, and check if you have the correct FASTA and SONIC files for it.
